dist: xenial   # required for Python >= 3.7
language: python

python:
  - 3.7
services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run src sh -c "./manage.py test && flake8"

