version: "3"

services:
  web:
    build: .
    container_name: django
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://user:user_passw@db/user_db
    volumes:
      - ./src:/app
      - static_data:/app/staticfiles
    restart: always
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_passw
      POSTGRES_DB: user_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/static
    ports:
      - 8000:8989
    restart: always
    depends_on:
      - web

volumes:
  static_data:
  pg_data:
