# Generated by Django 2.2.2 on 2019-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('priority', models.TextField(default='low')),
            ],
        ),
    ]
