# Generated by Django 2.2.2 on 2019-06-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
