# Generated by Django 2.2.2 on 2019-06-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_auto_20190606_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
