# Generated by Django 2.2.2 on 2019-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('high', 0), ('middle', 1), ('low', 2)], default='low'),
        ),
    ]
