# Generated by Django 2.2.2 on 2019-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('high', 0), ('middle', 1), ('low', 2)]),
        ),
    ]
