# Generated by Django 2.2.2 on 2019-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_auto_20190607_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
